// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0GG0NkOLUEiHTif1rb2ny20yAUCsDIlo',
    appId: '1:864960745673:web:a11addd678253ca820bd18',
    messagingSenderId: '864960745673',
    projectId: 'quizapp-a40c6',
    authDomain: 'quizapp-a40c6.firebaseapp.com',
    storageBucket: 'quizapp-a40c6.appspot.com',
    measurementId: 'G-YXDWKXLC3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmcyeDKenxdEvrMvsJ9R4fHLsD3pOiIPU',
    appId: '1:864960745673:android:c51f8a171b72201820bd18',
    messagingSenderId: '864960745673',
    projectId: 'quizapp-a40c6',
    storageBucket: 'quizapp-a40c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj3r_B3Q5VlbFwoEt_QxqETz9OuR2Tgv0',
    appId: '1:864960745673:ios:df362a3e2fd56b6620bd18',
    messagingSenderId: '864960745673',
    projectId: 'quizapp-a40c6',
    storageBucket: 'quizapp-a40c6.appspot.com',
    iosBundleId: 'com.example.flutterSampleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj3r_B3Q5VlbFwoEt_QxqETz9OuR2Tgv0',
    appId: '1:864960745673:ios:df362a3e2fd56b6620bd18',
    messagingSenderId: '864960745673',
    projectId: 'quizapp-a40c6',
    storageBucket: 'quizapp-a40c6.appspot.com',
    iosBundleId: 'com.example.flutterSampleProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0GG0NkOLUEiHTif1rb2ny20yAUCsDIlo',
    appId: '1:864960745673:web:2160eb0ff377400b20bd18',
    messagingSenderId: '864960745673',
    projectId: 'quizapp-a40c6',
    authDomain: 'quizapp-a40c6.firebaseapp.com',
    storageBucket: 'quizapp-a40c6.appspot.com',
    measurementId: 'G-Z0S839CGZ6',
  );
}
